version: '3.8'

services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5437:5432"
    entrypoint: ["bash", "-c", "chown -R postgres:postgres /var/lib/postgresql/data && chmod -R 700 /var/lib/postgresql/data && exec docker-entrypoint.sh postgres"]



  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - mongodb_data:/data/db



volumes:
  db_data:
  mongodb_data: